---
apiVersion: v1
kind: Namespace
metadata:
  name: jssm200
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-reader
  labels:
    origin: github.com_Yolean_kubernetes-kafka
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kafka-node-reader
  labels:
    origin: github.com_Yolean_kubernetes-kafka
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: jssm200
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-labler
  namespace: jssm200
  labels:
    origin: github.com_Yolean_kubernetes-kafka
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - update
  - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kafka-pod-labler
  namespace: jssm200
  labels:
    origin: github.com_Yolean_kubernetes-kafka
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-labler
subjects:
- kind: ServiceAccount
  name: default
  namespace: jssm200
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user
  namespace: jssm200
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: jssm200
  name: jssm200-user
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jssm200-user
  namespace: jssm200
subjects:
- kind: ServiceAccount
  name: user
  namespace: jssm200
roleRef:
  kind: Role
  name: jssm200-user
  apiGroup: rbac.authorization.k8s.io