kind: ConfigMap
metadata:
  name: jssm200-nginx
  namespace: jssm200
apiVersion: v1
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /usr/share/nginx/html/nginx-error.log;
    pid /run/nginx.pid;
    
    # Load dynamic modules. See /usr/share/nginx/README.dynamic.
    include /usr/share/nginx/modules/*.conf;
    
    events {
        worker_connections 102400;
        use epoll;
    }
    
    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
    
        proxy_headers_hash_max_size 51200;
        proxy_headers_hash_bucket_size 6400;
        access_log        /usr/share/nginx/html/nginx-default-access.log  main;
        charset utf-8;
        sendfile            on;
        tcp_nopush          on;
        tcp_nodelay         on;
        keepalive_timeout   65;
        types_hash_max_size 2048;
        client_header_timeout 10;
        client_body_timeout 10;
        send_timeout 10;
        server_tokens off;
        underscores_in_headers on;
        #开启gzip压缩
        gzip on;
        ##http的协议版本
        gzip_http_version 1.1;
        ##IE版本1-6不支持gzip压缩，关闭
        #gzip_disable 'MSIE[1-6].';
        ##需要压缩的文件格式 text/html默认会压缩，不用添加
        #gzip_types text/plain application/x-java script text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;
        gzip_types application/javascript text/plain application/json application/x-javascript application/css application/xml application/xml+rss text/javascript     application/x-httpd-php;
        ##设置压缩缓冲区大小，此处设置为4个8K内存作为压缩结果流缓存
        gzip_buffers 4 8k;
        ##压缩文件最小大小
        gzip_min_length 1k;
        ##压缩级别1-9
        gzip_comp_level 2;
        ##给响应头加个vary，告知客户端能否缓存
        gzip_vary on;
        ##反向代理时使用
        gzip_proxied off;
    
        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;
        include /etc/nginx/conf.d/*.conf;
    
    
    server {
        listen       80 default_server;
    #    server_name  localhost;
    #   access_log logs/80.log main;
    #   error_log logs/80.error;
        root         /data/dist/;
        #将所有请求转发给demo_pool池的应用处理
        client_max_body_size 11M;
     location / {
        index index.html index.htm default.htm default.html;
                }
           }
         }
---
apiVersion: apps/v1
#kind: Deployment
kind: DaemonSet
metadata:
  name: nginx-static
  namespace: jssm200
spec:
#  replicas: 3
  selector:
    matchLabels:
      app: nginx-static
  template:
    metadata:
      labels:
        app: nginx-static
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: dist
          mountPath: /data/dist
        - name: config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        livenessProbe:
          exec:
            command: ["cat","/etc/hosts"]
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3
      volumes:
      - name: dist
        nfs:                         
          server: 192.168.85.124
          path: "/data/dist"      
      - name: config
        configMap:
          name: jssm200-nginx

---
apiVersion: v1
kind: Service
metadata:
  name: jssm200-static
  namespace: jssm200
spec:
  ports:
  - port: 80
    name: jssm200-static
  type: ClusterIP
  selector:
    app: nginx-static
