apiVersion: v1
data:
  elasticsearch.yml: |-
    #cluster.name: "elasticsearch-0"
    network.host: 0.0.0.0
    http.cors.enabled: true
    http.cors.allow-origin: "*"
    path.logs: /usr/share/elasticsearch/logs
    xpack.security.enabled: true
    xpack.security.transport.ssl.enabled: true
    #discovery.seed_hosts: ["127.0.0.1", "[::1]"]
    cluster.initial_master_nodes: ["elasticsearch-0"]
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: elasticsearch
  namespace: elk
