---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: jssm200
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mongo
  namespace: jssm200
subsets:
  - addresses:
      - ip: 192.168.0.244
    ports:
      - port: 27017
