---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: jssm200
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql
  namespace: jssm200
subsets:
  - addresses:
      - ip: 192.168.0.203
    ports:
      - port: 3306
